[DEV] Improved yml files

diff --git a/.github/workflows/pullrequest.yml b/.github/workflows/pullrequest.yml
--- a/.github/workflows/pullrequest.yml
+++ b/.github/workflows/pullrequest.yml
@@ -1,7 +1,10 @@
-name: Branch
+name: Branches
 
 on:
   pull_request:
+    branches:
+      - '**' # Run on all branches
+  push:
     branches:
       - '**' # Run on all branches
 
@@ -34,39 +37,72 @@ jobs:
           api-level: 30
           build-tools: 30.0.3
 
-      - name: Decode and Save Signing Key
+      - name: Decode Keystore
         run: |
           mkdir -p $HOME/.android
-          echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > $HOME/.android/release.keystore
+          echo ${{secrets.SIGNING_KEY_BASE64}} > keystore-base64.txt
+          base64 -d keystore-base64.txt > $HOME/.android/release.keystore
+          ls -la $HOME/.android
+          ls -la $HOME/.android/release.keystore
+
+      - name: Verify Signing Key
+        run: |
+          keytool -list -v -keystore $HOME/.android/release.keystore -storepass $SIGNING_STORE_PASSWORD
 
       - name: Download Dependencies
-        run: ./gradlew build --scan --continue
+        run: ./gradlew dependencies --stacktrace
+
+      - name: Run Lint
+        run: ./gradlew lint --stacktrace
 
       - name: Assemble Release
         run: ./gradlew assembleRelease --stacktrace
 
+      - name: Verify APK Existence
+        run: |
+          echo "Listing contents of app/build/outputs/apk/release/"
+          ls -la app/build/outputs/apk/release/
+
       - name: Sign APK
         run: |
-          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
-          -keystore $HOME/.android/release.keystore \
-          -storepass ${{ secrets.SIGNING_STORE_PASSWORD }} \
-          -keypass ${{ secrets.SIGNING_KEY_PASSWORD }} \
-          app/build/outputs/apk/release/app-release-unsigned.apk \
-          ${{ secrets.SIGNING_KEY_ALIAS }}
+          if [ -f "app/build/outputs/apk/release/app-release-unsigned.apk" ]; then
+            jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
+              -keystore $HOME/.android/release.keystore \
+              -storepass $SIGNING_STORE_PASSWORD \
+              -keypass $SIGNING_KEY_PASSWORD \
+              app/build/outputs/apk/release/app-release-unsigned.apk \
+              $SIGNING_KEY_ALIAS
+          else
+            echo "app-release-unsigned.apk not found"
+            exit 1
+          fi
 
       - name: Verify Signature
-        run: jarsigner -verify app/build/outputs/apk/release/app-release-unsigned.apk
+        run: |
+          if [ -f "app/build/outputs/apk/release/app-release-unsigned.apk" ]; then
+            jarsigner -verify app/build/outputs/apk/release/app-release-unsigned.apk
+          else
+            echo "app-release-unsigned.apk not found"
+            exit 1
+          fi
 
       - name: Zipalign APK
-        run: ${ANDROID_SDK_ROOT}/build-tools/30.0.3/zipalign -v 4 app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release.apk
+        run: |
+          if [ -f "app/build/outputs/apk/release/app-release-unsigned.apk" ]; then
+            ${ANDROID_SDK_ROOT}/build-tools/30.0.3/zipalign -v 4 app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release-aligned.apk
+          else
+            echo "app-release-unsigned.apk not found"
+            exit 1
+          fi
 
       - name: Upload Release APK
         uses: actions/upload-artifact@v2
         with:
-          name: app-release.apk
-          path: app/build/outputs/apk/release/app-release.apk
+          name: app-release-aligned.apk
+          path: app/build/outputs/apk/release/app-release-aligned.apk
 
       - name: Bump Version Code and Commit
+        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
         run: |
           versionCode=$(grep versionCode app/build.gradle.kts | awk '{print $2}')
           newVersionCode=$((versionCode + 1))
